"""
B2b DHS element tiling — reconstructed 2026-08-04.

Original run: inline session script; exact run date unrecoverable.
Reconstruction source: results/gwas_modifiers/B2b_tiling_scores.csv

DHS element intervals are defined as the min–max range of positions
that appear in the original output file, at 25 bp step. The Stolzenburg
2017 / GSE52179 peak boundaries may extend beyond those limits; that
information is unrecoverable from the scored output alone.

Control sampling logic was NOT reproduced. The 450 control rows in
B2b_tiling_scores.csv (kind='control') were generated by a sampling
procedure whose interval definitions and matching criteria cannot be
recovered from the output. Those rows are preserved in the original
file; this script produces DHS rows only.

Scorer : CenterMaskScorer(ATAC, width=501, L2_DIFF)
Tissue : UBERON:0002048 (lung)
Step   : 25 bp

Usage:
    .venv/bin/python scripts/b2b_tiling.py
    .venv/bin/python scripts/b2b_tiling.py --dry-run

Output:
    results/gwas_modifiers/B2b_tiling_dhs_rerun.csv
"""

import argparse
import datetime
import os
import sys
import time

import numpy as np
import pandas as pd
from dotenv import load_dotenv

import alphagenome as _ag
AG_VERSION = getattr(_ag, "__version__", "unknown")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(ROOT, ".env"))
API_KEY = os.environ.get("ALPHAGENOME_API_KEY", "")
if not API_KEY:
    sys.exit("ERROR: Set ALPHAGENOME_API_KEY in .env")

from alphagenome.data import genome
from alphagenome.models import dna_client
from alphagenome.models.variant_scorers import (
    CenterMaskScorer, AggregationType, tidy_scores,
)
from alphagenome.models.dna_output import OutputType
import grpc

OUT_DIR  = os.path.join(ROOT, "results/gwas_modifiers")
ORIG_CSV = os.path.join(OUT_DIR, "B2b_tiling_scores.csv")
OUT_CSV  = os.path.join(OUT_DIR, "B2b_tiling_dhs_rerun.csv")
CKPT_CSV = os.path.join(OUT_DIR, ".B2b_tiling_ckpt.csv")

HALF    = dna_client.SEQUENCE_LENGTH_1MB // 2
TISSUE  = "UBERON:0002048"
STEP    = 25
BASES   = frozenset({"A", "C", "G", "T"})

ATAC_SCORER = CenterMaskScorer(
    requested_output=OutputType.ATAC,
    width=501,
    aggregation_type=AggregationType.L2_DIFF,
)


def load_element_definitions(orig_csv: str) -> tuple[list[dict], dict[int, str]]:
    """
    Read DHS element definitions from the original tiling output.

    Returns:
        elements : list of dicts with keys element, chrom, start, end, label,
                   dnase_score. start/end are the min/max scored positions.
        pos_ref  : dict mapping genomic position → reference allele.
    """
    df = pd.read_csv(orig_csv, keep_default_na=False)
    dhs = df[df["kind"] == "dhs"].copy()

    pos_ref: dict[int, str] = (
        dhs.drop_duplicates("pos")
        .set_index("pos")["ref"]
        .to_dict()
    )

    elements = []
    for elem, grp in dhs.groupby("element"):
        elements.append({
            "element":    elem,
            "chrom":      grp["chrom"].iloc[0],
            "start":      int(grp["pos"].min()),
            "end":        int(grp["pos"].max()),
            "label":      grp["label"].iloc[0],
            "dnase_score": int(grp["dnase_score"].iloc[0]),
        })
    return sorted(elements, key=lambda x: x["start"]), pos_ref


def generate_variants(elements: list[dict], pos_ref: dict[int, str]) -> list[dict]:
    """
    For each element, tile from start to end at STEP bp and yield all
    three non-reference SNVs per position.

    Positions not present in pos_ref (i.e. not in the original output)
    are skipped. This guarantees the generated set exactly matches the
    original DHS rows.
    """
    variants = []
    for el in elements:
        for pos in range(el["start"], el["end"] + STEP, STEP):
            if pos not in pos_ref:
                continue
            ref = pos_ref[pos]
            for alt in sorted(BASES - {ref}):
                variants.append({
                    "key":         f"dhs_{el['element']}_{pos}_{ref}_{alt}",
                    "kind":        "dhs",
                    "element":     el["element"],
                    "chrom":       el["chrom"],
                    "pos":         pos,
                    "ref":         ref,
                    "alt":         alt,
                    "label":       el["label"],
                    "dnase_score": el["dnase_score"],
                })
    return variants


def score_variant(model, chrom: str, pos: int, ref: str, alt: str) -> float:
    """Score one variant; returns raw ATAC L2_DIFF for TISSUE, or NaN."""
    variant  = genome.Variant(chromosome=chrom, position=pos,
                              reference_bases=ref, alternate_bases=alt)
    interval = genome.Interval(chromosome=chrom,
                               start=pos - HALF, end=pos + HALF)
    raw  = model.score_variants(
        intervals=[interval], variants=[variant],
        variant_scorers=[ATAC_SCORER], progress_bar=False,
    )
    tidy = tidy_scores(raw)
    rows = tidy[
        (tidy["ontology_curie"] == TISSUE) &
        (tidy["output_type"] == "ATAC")
    ]
    if rows.empty or rows["raw_score"].isna().all():
        return float("nan")
    return float(rows["raw_score"].abs().max())


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true",
                    help="Print variant list and exit without scoring")
    args = ap.parse_args()

    elements, pos_ref = load_element_definitions(ORIG_CSV)
    variants = generate_variants(elements, pos_ref)

    print(f"Source          : {ORIG_CSV}")
    print(f"Elements        : {len(elements)}")
    print(f"Variants        : {len(variants)}")
    print(f"Tissue          : {TISSUE}")
    print(f"Scorer          : CenterMaskScorer(ATAC, 501, L2_DIFF)")
    print(f"alphagenome     : {AG_VERSION}")

    if args.dry_run:
        print("\nFirst 5 variants:")
        for v in variants[:5]:
            print(f"  {v['key']}")
        print(f"\nOutput would go to: {OUT_CSV}")
        return

    RUN_UTC = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )

    completed: dict[str, float] = {}
    ckpt_rows: list[dict] = []
    if os.path.exists(CKPT_CSV):
        ckpt = pd.read_csv(CKPT_CSV)
        completed = dict(zip(ckpt["key"], ckpt["atac_l2d_raw"]))
        ckpt_rows = ckpt.to_dict("records")
        print(f"\nResuming from checkpoint: {len(completed)} done")

    remaining = [v for v in variants if v["key"] not in completed]
    print(f"\nConnecting to AlphaGenome API...")
    model = dna_client.create(API_KEY)
    print(f"Connected. {len(remaining)} variants to score.\n")

    new_count = 0
    for i, v in enumerate(remaining, 1):
        if i == 1 or i % 50 == 0:
            print(
                f"  [{i}/{len(remaining)}] {v['chrom']}:{v['pos']} "
                f"{v['ref']}>{v['alt']}  ({v['element']})",
                flush=True,
            )
        backoff = 15
        for attempt in range(6):
            try:
                score = score_variant(model, v["chrom"], v["pos"], v["ref"], v["alt"])
                row = {
                    **v,
                    "atac_l2d_raw": score,
                    "run_date_utc": RUN_UTC,
                    "ag_version":   AG_VERSION,
                }
                ckpt_rows.append(row)
                new_count += 1
                if new_count % 50 == 0:
                    pd.DataFrame(ckpt_rows).to_csv(CKPT_CSV, index=False)
                break
            except grpc.RpcError as e:
                code = e.code()
                if code in (grpc.StatusCode.RESOURCE_EXHAUSTED,
                            grpc.StatusCode.UNAVAILABLE):
                    print(f"    rate-limit ({attempt+1}/6) — sleep {backoff}s",
                          flush=True)
                else:
                    print(f"    gRPC {code} — sleep {backoff}s", flush=True)
                time.sleep(backoff)
                backoff = min(backoff * 2, 300)
            except Exception as exc:
                print(f"    ERROR: {exc}", flush=True)
                break

    pd.DataFrame(ckpt_rows).to_csv(CKPT_CSV, index=False)
    final = pd.DataFrame(ckpt_rows)
    final.to_csv(OUT_CSV, index=False)
    print(f"\nWritten {len(final)} rows to {OUT_CSV}")

    if len(final) == len(variants) and os.path.exists(CKPT_CSV):
        os.remove(CKPT_CSV)
        print("Checkpoint removed.")

    scored = final["atac_l2d_raw"].notna().sum()
    print(f"Scored: {scored}/{len(final)} ({len(final)-scored} NaN)")


if __name__ == "__main__":
    main()
